name: Client CI

on: 
  push:

jobs:
  tests:
    name: Test
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          working-directory: client/
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test:unit  

  build:
    name: Build
    needs: [tests]
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
#         push: ${{ github.head_ref == 'master' }}
          push: true
          tags: icarooliv/trab-individual-client:latest
          cache-from: type=registry,ref=icarooliv/trab-individual-client:latest
          cache-to: type=inline
          context: ./client
          file: ./client/Dockerfile.production
    
